<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-25 16:55:18                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoCompanyMember extends AutoProtoCompanyMember {/*_*/}
?>