<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:09                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoDeal extends AutoProtoDeal {/*_*/}
?>