<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2012-02-03 22:39:40                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoAjaxResponseData extends AutoProtoAjaxResponseData {/*_*/}
?>