<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-26 13:10:55                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoProject extends AutoProtoProject {/*_*/}
?>