<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAbstractPointDAO extends StorableDAO
	{
		// no get{Table,ObjectName,Sequence} for abstract class
		
		public function getSequence()
		{
			return 'abstract_point_id';
		}
	}
?>