<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAutologinTokenDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'autologin_token';
		}
		
		public function getObjectName()
		{
			return 'AutologinToken';
		}
		
		public function getSequence()
		{
			return 'uuid';
		}
	}
?>