<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:09                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCompanyProfileDAO extends CreatedAndModifiedDAO
	{
		public function getTable()
		{
			return 'company_profile';
		}
		
		public function getObjectName()
		{
			return 'CompanyProfile';
		}
		
		public function getSequence()
		{
			return 'company_profile_id';
		}
	}
?>