<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-26 13:10:55                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTaskDAO extends BaseTaskModelDAO
	{
		public function getTable()
		{
			return 'task';
		}
		
		public function getObjectName()
		{
			return 'Task';
		}
		
		public function getSequence()
		{
			return 'task_id';
		}
	}
?>