<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-25 00:59:32                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAuthDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'auth';
		}
		
		public function getObjectName()
		{
			return 'Auth';
		}
		
		public function getSequence()
		{
			return 'auth_id';
		}
	}
?>