<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoMemberDAO extends CreatedAndModifiedDAO
	{
		public function getTable()
		{
			return 'member';
		}
		
		public function getObjectName()
		{
			return 'Member';
		}
		
		public function getSequence()
		{
			return 'member_id';
		}
	}
?>