<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreatedAndModifiedDAO extends StorableDAO
	{
		// no get{Table,ObjectName,Sequence} for abstract class
		
		public function getSequence()
		{
			return 'created_and_modified_id';
		}
	}
?>