<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2012-02-02 18:20:11                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class CreatedAndModifiedDAO extends AutoCreatedAndModifiedDAO
	{
		// nothing here yet
            
            public function save(CreatedAndModified $object) {
                $object->setDateModify(Timestamp::makeNow());
                parent::save($object);
            }

            public function add(CreatedAndModified $object) {
                $object->setDateCreate(Timestamp::makeNow());
                $object->setDateModify(Timestamp::makeNow());
                parent::add($object);
            }
            
	}
?>