<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class MemberDAO extends AutoMemberDAO
	{
		// your brilliant stuff goes here
	}
?>