<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class PointDAO extends AutoPointDAO
	{
		// your brilliant stuff goes here
	}
?>