<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class StoryMembersDAO extends ManyToManyLinked
	{
		public function __construct(Story $story, $lazy = false)
		{
			parent::__construct(
				$story,
				Member::dao(),
				$lazy
			);
		}
		
		/**
		 * @return StoryMembersDAO
		**/
		public static function create(Story $story, $lazy = false)
		{
			return new self($story, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'story_member';
		}
		
		public function getChildIdField()
		{
			return 'member_id';
		}
		
		public function getParentIdField()
		{
			return 'story_id';
		}
	}
?>