<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class TripMembersDAO extends OneToManyLinked
	{
		public function __construct(Trip $trip, $lazy = false)
		{
			parent::__construct(
				$trip,
				Member::dao(),
				$lazy
			);
		}
		
		/**
		 * @return TripMembersDAO
		**/
		public static function create(Trip $trip, $lazy = false)
		{
			return new self($trip, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'trip_id';
		}
	}
?>