<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-25 00:59:32                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserFriendsDAO extends ManyToManyLinked
	{
		public function __construct(User $user, $lazy = false)
		{
			parent::__construct(
				$user,
				User::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserFriendsDAO
		**/
		public static function create(User $user, $lazy = false)
		{
			return new self($user, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'user_user';
		}
		
		public function getChildIdField()
		{
			return 'user_id';
		}
		
		public function getParentIdField()
		{
			return 'user_id';
		}
	}
?>