<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUserAccountIssue extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'UserAccountIssue', 8, true, true, false, null, null),
						'userAccount' => LightMetaProperty::fill(new LightMetaProperty(), 'userAccount', 'user_account_id', 'integerIdentifier', 'UserAccount', null, true, false, false, 1, 3),
						'value' => LightMetaProperty::fill(new LightMetaProperty(), 'value', null, 'float', null, 4, true, true, false, null, null),
						'balance' => LightMetaProperty::fill(new LightMetaProperty(), 'balance', null, 'float', null, 4, true, true, false, null, null),
						'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>