<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-26 13:10:55                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoProject extends ProtoBaseTaskModel
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Project', 8, true, true, false, null, null),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
						'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null),
						'companyExecutor' => LightMetaProperty::fill(new LightMetaProperty(), 'companyExecutor', 'company_executor_id', 'integerIdentifier', 'Company', null, true, false, false, 1, 3),
						'companyClient' => LightMetaProperty::fill(new LightMetaProperty(), 'companyClient', 'company_client_id', 'integerIdentifier', 'Company', null, false, false, false, 1, 3),
						'requirements' => LightMetaProperty::fill(new LightMetaProperty(), 'requirements', 'requirements_id', 'identifierList', 'Requirement', null, false, false, false, 2, null)
					)
				);
		}
	}
?>