<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUserAccount extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'UserAccount', 8, true, true, false, null, null),
						'freeUntilDate' => LightMetaProperty::fill(new LightMetaProperty(), 'freeUntilDate', 'free_until_date', 'date', 'Date', null, true, true, false, null, null),
						'balance' => LightMetaProperty::fill(new LightMetaProperty(), 'balance', null, 'float', null, 4, true, true, false, null, null),
						'bonus' => LightMetaProperty::fill(new LightMetaProperty(), 'bonus', null, 'float', null, 4, true, true, false, null, null),
						'issues' => LightMetaProperty::fill(new LightMetaProperty(), 'issues', 'issues_id', 'identifierList', 'UserAccountIssue', null, false, false, false, 2, null)
					)
				);
		}
	}
?>