<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAutologinToken extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'uuidIdentifier', 'AutologinToken', null, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'integerIdentifier', 'User', null, true, false, false, 1, 3),
				'createDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createDate', 'create_date', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'lastActivityDate' => LightMetaProperty::fill(new LightMetaProperty(), 'lastActivityDate', 'last_activity_date', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'expireDate' => LightMetaProperty::fill(new LightMetaProperty(), 'expireDate', 'expire_date', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'lastActivityIp' => LightMetaProperty::fill(new LightMetaProperty(), 'lastActivityIp', 'last_activity_ip', 'string', null, 30, false, true, false, null, null)
			);
		}
	}
?>