<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoMember extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Member', 8, true, true, false, null, null),
						'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'integerIdentifier', 'User', null, true, false, false, 1, 3),
						'trip' => LightMetaProperty::fill(new LightMetaProperty(), 'trip', 'trip_id', 'integerIdentifier', 'Trip', null, true, false, false, 1, 3),
						'status' => LightMetaProperty::fill(new LightMetaProperty(), 'status', 'status_id', 'enumeration', 'MemberStatus', null, true, false, false, 1, 3)
					)
				);
		}
	}
?>