<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoPoint extends ProtoAbstractPoint
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Point', 8, true, true, false, null, null),
						'trip' => LightMetaProperty::fill(new LightMetaProperty(), 'trip', 'trip_id', 'integerIdentifier', 'Trip', null, true, false, false, 1, 3),
						'location' => LightMetaProperty::fill(new LightMetaProperty(), 'location', 'location_id', 'integerIdentifier', 'Point', null, false, false, false, 1, 3),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
						'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null),
						'dateStart' => LightMetaProperty::fill(new LightMetaProperty(), 'dateStart', 'date_start', 'timestamp', 'Timestamp', null, true, true, false, null, null),
						'dateEnd' => LightMetaProperty::fill(new LightMetaProperty(), 'dateEnd', 'date_end', 'timestamp', 'Timestamp', null, true, true, false, null, null)
					)
				);
		}
	}
?>