<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-25 16:55:18                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoDeal extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Deal', 8, true, true, false, null, null),
						'client' => LightMetaProperty::fill(new LightMetaProperty(), 'client', 'client_id', 'integerIdentifier', 'Company', null, true, false, false, 1, 3),
						'executor' => LightMetaProperty::fill(new LightMetaProperty(), 'executor', 'executor_id', 'integerIdentifier', 'Company', null, true, false, false, 1, 3),
						'dateStart' => LightMetaProperty::fill(new LightMetaProperty(), 'dateStart', 'date_start', 'timestamp', 'Timestamp', null, false, true, false, null, null),
						'dateEnd' => LightMetaProperty::fill(new LightMetaProperty(), 'dateEnd', 'date_end', 'timestamp', 'Timestamp', null, false, true, false, null, null),
						'costTotal' => LightMetaProperty::fill(new LightMetaProperty(), 'costTotal', 'cost_total', 'float', null, 4, false, true, false, null, null)
					)
				);
		}
	}
?>