<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-04 21:04:45                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoStory extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Story', 8, true, true, false, null, null),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
						'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null),
						'dateStart' => LightMetaProperty::fill(new LightMetaProperty(), 'dateStart', 'date_start', 'timestamp', 'Timestamp', null, true, true, false, null, null),
						'owner' => LightMetaProperty::fill(new LightMetaProperty(), 'owner', 'owner_id', 'integerIdentifier', 'User', null, true, false, false, 1, 3),
						'members' => LightMetaProperty::fill(new LightMetaProperty(), 'members', 'members_id', 'identifierList', 'Member', null, false, false, false, 2, null),
						'public' => LightMetaProperty::fill(new LightMetaProperty(), 'public', null, 'boolean', null, null, false, true, false, null, null)
					)
				);
		}
	}
?>