<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-26 13:10:54                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBaseTaskModel extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'dateStart' => LightMetaProperty::fill(new LightMetaProperty(), 'dateStart', 'date_start', 'timestamp', 'Timestamp', null, false, true, false, null, null),
						'dateEnd' => LightMetaProperty::fill(new LightMetaProperty(), 'dateEnd', 'date_end', 'timestamp', 'Timestamp', null, false, true, false, null, null),
						'members' => LightMetaProperty::fill(new LightMetaProperty(), 'members', 'members_id', 'identifierList', 'CompanyMember', null, false, false, false, 2, null),
						'memberCreatedBy' => LightMetaProperty::fill(new LightMetaProperty(), 'memberCreatedBy', 'member_created_by_id', 'integerIdentifier', 'CompanyMember', null, false, false, false, 1, 3),
						'memberExecutor' => LightMetaProperty::fill(new LightMetaProperty(), 'memberExecutor', 'member_executor_id', 'integerIdentifier', 'CompanyMember', null, false, false, false, 1, 3),
						'memberClient' => LightMetaProperty::fill(new LightMetaProperty(), 'memberClient', 'member_client_id', 'integerIdentifier', 'CompanyMember', null, false, false, false, 1, 3),
						'costHour' => LightMetaProperty::fill(new LightMetaProperty(), 'costHour', 'cost_hour', 'float', null, 4, false, true, false, null, null),
						'costPublic' => LightMetaProperty::fill(new LightMetaProperty(), 'costPublic', 'cost_public', 'float', null, 4, false, true, false, null, null),
						'costReal' => LightMetaProperty::fill(new LightMetaProperty(), 'costReal', 'cost_real', 'float', null, 4, false, true, false, null, null),
						'percentComplete' => LightMetaProperty::fill(new LightMetaProperty(), 'percentComplete', 'percent_complete', 'integer', null, 4, false, true, false, null, null),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'BaseTaskModel', 8, true, true, false, null, null)
					)
				);
		}
	}
?>