<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-25 00:59:32                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoStoryPeriod extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'StoryPeriod', 8, true, true, false, null, null),
						'story' => LightMetaProperty::fill(new LightMetaProperty(), 'story', 'story_id', 'integerIdentifier', 'Story', null, true, false, false, 1, null),
						'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, null, false, true, false, null, null),
						'date' => LightMetaProperty::fill(new LightMetaProperty(), 'date', null, 'timestamp', 'Timestamp', null, true, true, false, null, null)
					)
				);
		}
	}
?>