<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAuth extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Auth', 8, true, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 255, false, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 255, false, true, false, null, null)
			);
		}
	}
?>