<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:42:42                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUser extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'User', 8, true, true, false, null, null),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
						'firstName' => LightMetaProperty::fill(new LightMetaProperty(), 'firstName', 'first_name', 'string', null, 255, true, true, false, null, null),
						'middleName' => LightMetaProperty::fill(new LightMetaProperty(), 'middleName', 'middle_name', 'string', null, 255, false, true, false, null, null),
						'lastName' => LightMetaProperty::fill(new LightMetaProperty(), 'lastName', 'last_name', 'string', null, 255, false, true, false, null, null),
						'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 255, true, true, false, null, null),
						'auth' => LightMetaProperty::fill(new LightMetaProperty(), 'auth', 'auth_id', 'integerIdentifier', 'Auth', null, true, false, false, 1, 3)
					)
				);
		}
	}
?>