<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-25 16:55:18                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCompany extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Company', 8, true, true, false, null, null),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
						'createdByUser' => LightMetaProperty::fill(new LightMetaProperty(), 'createdByUser', 'created_by_user_id', 'integerIdentifier', 'User', null, true, false, false, 1, 3),
						'members' => LightMetaProperty::fill(new LightMetaProperty(), 'members', 'members_id', 'identifierList', 'CompanyMember', null, false, false, false, 2, null)
					)
				);
		}
	}
?>