<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoMember extends ProtoCreatedAndModified
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Member', 8, true, true, false, null, null),
						'title' => LightMetaProperty::fill(new LightMetaProperty(), 'title', null, 'string', null, 255, false, true, false, null, null),
						'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'integerIdentifier', 'User', null, true, false, false, 1, 3),
						'story' => LightMetaProperty::fill(new LightMetaProperty(), 'story', 'story_id', 'integerIdentifier', 'Story', null, true, false, false, 1, 3),
						'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enumeration', 'MemberType', null, true, false, false, 1, 3),
						'status' => LightMetaProperty::fill(new LightMetaProperty(), 'status', 'status_id', 'enumeration', 'MemberStatus', null, true, false, false, 1, 3)
					)
				);
		}
	}
?>