<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUserAccountIssue extends CreatedAndModified
	{
		protected $userAccount = null;
		protected $userAccountId = null;
		protected $value = 0;
		protected $balance = 0;
		protected $description = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'userAccountId', 'value', 'balance', 'description')
			);
		}
		
		/**
		 * @return UserAccount
		**/
		public function getUserAccount()
		{
			if (!$this->userAccount && $this->userAccountId) {
				$this->userAccount = UserAccount::dao()->getById($this->userAccountId);
			}
			
			return $this->userAccount;
		}
		
		public function getUserAccountId()
		{
			return $this->userAccountId;
		}
		
		/**
		 * @return UserAccountIssue
		**/
		public function setUserAccount(UserAccount $userAccount)
		{
			$this->userAccount = $userAccount;
			$this->userAccountId = $userAccount->getId();
			
			return $this;
		}
		
		/**
		 * @return UserAccountIssue
		**/
		public function setUserAccountId($id)
		{
			$this->userAccount = null;
			$this->userAccountId = $id;
			
			return $this;
		}
		
		/**
		 * @return UserAccountIssue
		**/
		public function dropUserAccount()
		{
			$this->userAccount = null;
			$this->userAccountId = null;
			
			return $this;
		}
		
		public function getValue()
		{
			return $this->value;
		}
		
		/**
		 * @return UserAccountIssue
		**/
		public function setValue($value)
		{
			$this->value = $value;
			
			return $this;
		}
		
		public function getBalance()
		{
			return $this->balance;
		}
		
		/**
		 * @return UserAccountIssue
		**/
		public function setBalance($balance)
		{
			$this->balance = $balance;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return UserAccountIssue
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
	}
?>