<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-25 00:59:32                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoStoryPeriod extends CreatedAndModified
	{
		protected $story = null;
		protected $description = null;
		protected $date = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'story', 'description', 'date')
			);
		}
		
		/**
		 * @return Story
		**/
		public function getStory()
		{
			return $this->story;
		}
		
		/**
		 * @return StoryPeriod
		**/
		public function setStory(Story $story)
		{
			$this->story = $story;
			
			return $this;
		}
		
		/**
		 * @return StoryPeriod
		**/
		public function dropStory()
		{
			$this->story = null;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return StoryPeriod
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getDate()
		{
			return $this->date;
		}
		
		/**
		 * @return StoryPeriod
		**/
		public function setDate(Timestamp $date)
		{
			$this->date = $date;
			
			return $this;
		}
		
		/**
		 * @return StoryPeriod
		**/
		public function dropDate()
		{
			$this->date = null;
			
			return $this;
		}
	}
?>