<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-25 17:25:39                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCompanyMember extends CreatedAndModified
	{
		protected $company = null;
		protected $companyId = null;
		protected $user = null;
		protected $userId = null;
		protected $status = null;
		protected $statusId = null;
		protected $costHour = 0;
		protected $position = null;
		protected $canAdmin = false;
		protected $canSeeDeals = false;
		protected $canSeeProjects = false;
		protected $canSeeRequirements = false;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'companyId', 'userId', 'statusId', 'costHour', 'position', 'canAdmin', 'canSeeDeals', 'canSeeProjects', 'canSeeRequirements')
			);
		}
		
		/**
		 * @return Company
		**/
		public function getCompany()
		{
			if (!$this->company && $this->companyId) {
				$this->company = Company::dao()->getById($this->companyId);
			}
			
			return $this->company;
		}
		
		public function getCompanyId()
		{
			return $this->companyId;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCompany(Company $company)
		{
			$this->company = $company;
			$this->companyId = $company->getId();
			
			return $this;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCompanyId($id)
		{
			$this->company = null;
			$this->companyId = $id;
			
			return $this;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function dropCompany()
		{
			$this->company = null;
			$this->companyId = null;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->userId;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user->getId();
			
			return $this;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		/**
		 * @return EnumObjectStatus
		**/
		public function getStatus()
		{
			if (!$this->status && $this->statusId) {
				$this->status = new EnumObjectStatus($this->statusId);
			}
			
			return $this->status;
		}
		
		public function getStatusId()
		{
			return $this->statusId;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setStatus(EnumObjectStatus $status)
		{
			$this->status = $status;
			$this->statusId = $status->getId();
			
			return $this;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setStatusId($id)
		{
			$this->status = null;
			$this->statusId = $id;
			
			return $this;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function dropStatus()
		{
			$this->status = null;
			$this->statusId = null;
			
			return $this;
		}
		
		public function getCostHour()
		{
			return $this->costHour;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCostHour($costHour)
		{
			$this->costHour = $costHour;
			
			return $this;
		}
		
		public function getPosition()
		{
			return $this->position;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setPosition($position)
		{
			$this->position = $position;
			
			return $this;
		}
		
		public function getCanAdmin()
		{
			return $this->canAdmin;
		}
		
		public function isCanAdmin()
		{
			return $this->canAdmin;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCanAdmin($canAdmin = false)
		{
			$this->canAdmin = ($canAdmin === true);
			
			return $this;
		}
		
		public function getCanSeeDeals()
		{
			return $this->canSeeDeals;
		}
		
		public function isCanSeeDeals()
		{
			return $this->canSeeDeals;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCanSeeDeals($canSeeDeals = false)
		{
			$this->canSeeDeals = ($canSeeDeals === true);
			
			return $this;
		}
		
		public function getCanSeeProjects()
		{
			return $this->canSeeProjects;
		}
		
		public function isCanSeeProjects()
		{
			return $this->canSeeProjects;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCanSeeProjects($canSeeProjects = false)
		{
			$this->canSeeProjects = ($canSeeProjects === true);
			
			return $this;
		}
		
		public function getCanSeeRequirements()
		{
			return $this->canSeeRequirements;
		}
		
		public function isCanSeeRequirements()
		{
			return $this->canSeeRequirements;
		}
		
		/**
		 * @return CompanyMember
		**/
		public function setCanSeeRequirements($canSeeRequirements = false)
		{
			$this->canSeeRequirements = ($canSeeRequirements === true);
			
			return $this;
		}
	}
?>