<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAuth extends IdentifiableObject
	{
		protected $email = null;
		protected $password = null;
		
		public function __sleep()
		{
			return array('id', 'email', 'password');
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return Auth
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return Auth
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
	}
?>