<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAjaxResponseData extends AjaxResponse
	{
		protected $data = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('data')
			);
		}
		
		public function getData()
		{
			return $this->data;
		}
		
		/**
		 * @return AjaxResponseData
		**/
		public function setData($data)
		{
			$this->data = $data;
			
			return $this;
		}
	}
?>