<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:08                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAutologinToken extends IdentifiableObject
	{
		protected $user = null;
		protected $userId = null;
		protected $createDate = null;
		protected $lastActivityDate = null;
		protected $expireDate = null;
		protected $lastActivityIp = null;
		
		public function __sleep()
		{
			return array('id', 'userId', 'createDate', 'lastActivityDate', 'expireDate', 'lastActivityIp');
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->userId;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user->getId();
			
			return $this;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreateDate()
		{
			return $this->createDate;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function setCreateDate(Timestamp $createDate)
		{
			$this->createDate = $createDate;
			
			return $this;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function dropCreateDate()
		{
			$this->createDate = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getLastActivityDate()
		{
			return $this->lastActivityDate;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function setLastActivityDate(Timestamp $lastActivityDate)
		{
			$this->lastActivityDate = $lastActivityDate;
			
			return $this;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function dropLastActivityDate()
		{
			$this->lastActivityDate = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getExpireDate()
		{
			return $this->expireDate;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function setExpireDate(Timestamp $expireDate)
		{
			$this->expireDate = $expireDate;
			
			return $this;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function dropExpireDate()
		{
			$this->expireDate = null;
			
			return $this;
		}
		
		public function getLastActivityIp()
		{
			return $this->lastActivityIp;
		}
		
		/**
		 * @return AutologinToken
		**/
		public function setLastActivityIp($lastActivityIp)
		{
			$this->lastActivityIp = $lastActivityIp;
			
			return $this;
		}
	}
?>