<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoPoint extends AbstractPoint
	{
		protected $trip = null;
		protected $tripId = null;
		protected $location = null;
		protected $locationId = null;
		protected $description = null;
		protected $dateStart = null;
		protected $dateEnd = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'tripId', 'locationId', 'name', 'description', 'dateStart', 'dateEnd')
			);
		}
		
		/**
		 * @return Trip
		**/
		public function getTrip()
		{
			if (!$this->trip && $this->tripId) {
				$this->trip = Trip::dao()->getById($this->tripId);
			}
			
			return $this->trip;
		}
		
		public function getTripId()
		{
			return $this->tripId;
		}
		
		/**
		 * @return Point
		**/
		public function setTrip(Trip $trip)
		{
			$this->trip = $trip;
			$this->tripId = $trip->getId();
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function setTripId($id)
		{
			$this->trip = null;
			$this->tripId = $id;
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function dropTrip()
		{
			$this->trip = null;
			$this->tripId = null;
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function getLocation()
		{
			if (!$this->location && $this->locationId) {
				$this->location = Point::dao()->getById($this->locationId);
			}
			
			return $this->location;
		}
		
		public function getLocationId()
		{
			return $this->locationId;
		}
		
		/**
		 * @return Point
		**/
		public function setLocation(Point $location)
		{
			$this->location = $location;
			$this->locationId = $location->getId();
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function setLocationId($id)
		{
			$this->location = null;
			$this->locationId = $id;
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function dropLocation()
		{
			$this->location = null;
			$this->locationId = null;
			
			return $this;
		}
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return Point
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getDateStart()
		{
			return $this->dateStart;
		}
		
		/**
		 * @return Point
		**/
		public function setDateStart(Timestamp $dateStart)
		{
			$this->dateStart = $dateStart;
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function dropDateStart()
		{
			$this->dateStart = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getDateEnd()
		{
			return $this->dateEnd;
		}
		
		/**
		 * @return Point
		**/
		public function setDateEnd(Timestamp $dateEnd)
		{
			$this->dateEnd = $dateEnd;
			
			return $this;
		}
		
		/**
		 * @return Point
		**/
		public function dropDateEnd()
		{
			$this->dateEnd = null;
			
			return $this;
		}
	}
?>