<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoMember extends CreatedAndModified
	{
		protected $user = null;
		protected $userId = null;
		protected $trip = null;
		protected $tripId = null;
		protected $status = null;
		protected $statusId = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'userId', 'tripId', 'statusId')
			);
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->userId;
		}
		
		/**
		 * @return Member
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user->getId();
			
			return $this;
		}
		
		/**
		 * @return Member
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return Member
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		/**
		 * @return Trip
		**/
		public function getTrip()
		{
			if (!$this->trip && $this->tripId) {
				$this->trip = Trip::dao()->getById($this->tripId);
			}
			
			return $this->trip;
		}
		
		public function getTripId()
		{
			return $this->tripId;
		}
		
		/**
		 * @return Member
		**/
		public function setTrip(Trip $trip)
		{
			$this->trip = $trip;
			$this->tripId = $trip->getId();
			
			return $this;
		}
		
		/**
		 * @return Member
		**/
		public function setTripId($id)
		{
			$this->trip = null;
			$this->tripId = $id;
			
			return $this;
		}
		
		/**
		 * @return Member
		**/
		public function dropTrip()
		{
			$this->trip = null;
			$this->tripId = null;
			
			return $this;
		}
		
		/**
		 * @return MemberStatus
		**/
		public function getStatus()
		{
			if (!$this->status && $this->statusId) {
				$this->status = new MemberStatus($this->statusId);
			}
			
			return $this->status;
		}
		
		public function getStatusId()
		{
			return $this->statusId;
		}
		
		/**
		 * @return Member
		**/
		public function setStatus(MemberStatus $status)
		{
			$this->status = $status;
			$this->statusId = $status->getId();
			
			return $this;
		}
		
		/**
		 * @return Member
		**/
		public function setStatusId($id)
		{
			$this->status = null;
			$this->statusId = $id;
			
			return $this;
		}
		
		/**
		 * @return Member
		**/
		public function dropStatus()
		{
			$this->status = null;
			$this->statusId = null;
			
			return $this;
		}
	}
?>