<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2014-09-24 13:38:09                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCompanyProfile extends CreatedAndModified
	{
		protected $site = null;
		
		public function __sleep()
		{
			return array_merge(
				parent::__sleep(),
				array('id', 'site')
			);
		}
		
		public function getSite()
		{
			return $this->site;
		}
		
		/**
		 * @return CompanyProfile
		**/
		public function setSite($site)
		{
			$this->site = $site;
			
			return $this;
		}
	}
?>