<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2012-02-03 22:39:40                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AjaxResponseData extends AutoAjaxResponseData implements Prototyped
	{
		/**
		 * @return AjaxResponseData
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoAjaxResponseData
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAjaxResponseData');
		}
		
		// your brilliant stuff goes here
	}
?>