<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2012-02-02 18:20:11                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Auth extends AutoAuth implements Prototyped, DAOConnected
	{
		/**
		 * @return Auth
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return AuthDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('AuthDAO');
		}
		
		/**
		 * @return ProtoAuth
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAuth');
		}
		
		// your brilliant stuff goes here
                
                public static function encodePassword($str){
                    return md5(sha1($str).'-secret_');
                }
	}
?>