<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2012-02-03 22:25:26                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AutologinToken extends AutoAutologinToken implements Prototyped, DAOConnected
	{
		/**
		 * @return AutologinToken
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return AutologinTokenDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('AutologinTokenDAO');
		}
		
		/**
		 * @return ProtoAutologinToken
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAutologinToken');
		}
		
		// your brilliant stuff goes here
	}
?>