<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

class MemberStatus extends Enumeration
{
    const WAITING = 1;
    const ACTIVE = 2;
    const REJECTED = 3;
    const BANNED = 4;

    protected $names= array(
        self::WAITING=>'Waiting',
        self::ACTIVE=>'Active',
        self::REJECTED=>'Rejected',
        self::BANNED=>'Banned',
    );

    /**
     * @return \self 
     */
    public static function waiting(){
        return new self(self::WAITING);
    }
    /**
     * @return \self 
     */
    public static function active(){
        return new self(self::ACTIVE);
    }
    /**
     * @return \self 
     */
    public static function rejected(){
        return new self(self::REJECTED);
    }
    /**
     * @return \self 
     */
    public static function banned(){
        return new self(self::BANNED);
    }
    
    
}
?>