<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

class MemberType extends Enumeration
{
    // implement me!
    const OWNER = 1;
    const MEMBER = 2;
    const WATCHER = 3;
    
    protected $names= array(
        self::OWNER=>'Owner',
        self::MEMBER=>'Member',
        self::WATCHER=>'Watcher',
    );
    
    /**
     * @return \self 
     */
    public static function owner(){
        return new self(self::OWNER);
    }
    /**
     * @return \self 
     */
    public static function member(){
        return new self(self::MEMBER);
    }
    /**
     * @return \self 
     */
    public static function watcher(){
        return new self(self::WATCHER);
    }
}
?>