<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-30 23:34:59                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Member extends AutoMember implements Prototyped, DAOConnected, IArrayable
	{
		/**
		 * @return Member
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return MemberDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('MemberDAO');
		}
		
		/**
		 * @return ProtoMember
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoMember');
		}

                
                
                
                public function toArray() {
                    return array(
                        'user'=>array(
                            'id'=>$this->getUserId(),
                            'name'=>$this->getUser()->getName()
                        ),
                        'story'=>array(
                            'id'=>$this->getStoryId(),
                            'name'=>$this->getStory()->getName(),
                        ),
                        'title'=>$this->getTitle(),
                        'type'=>$this->getTypeId(),
                        'status'=>$this->getStatusId(),
                    );
                }
                
                public function toExtendedArray() {
                    $arr = parent::toExtendedArray();
                    
                    return $arr;
                }
	}
?>