<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class Point extends AutoPoint implements Prototyped, DAOConnected
	{
		/**
		 * @return Point
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PointDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PointDAO');
		}
		
		/**
		 * @return ProtoPoint
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoPoint');
		}
		
		// your brilliant stuff goes here
	}
?>