<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-04-21 21:29:01                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

class PointType extends Enumeration
{
    const GET = 1;
    const GET_LIST = 2;
    const CREATE = 3;
    const UPDATE = 4;
    const DELETE = 5;
    const SORT = 6;

    protected $names= array(
        self::GET=>'Get item',
        self::GET_LIST=>'Get items list',
        self::CREATE=>'Create item',
        self::UPDATE=>'Update item',
        self::DELETE=>'Delete item',
        self::SORT=>'Sort items',
    );

    /**
     * @return \self 
     */
    public static function get(){
        return new self(self::GET);
    }

    /**
     * @return \self 
     */
    public static function getList(){
        return new self(self::GET_LIST);
    }

    /**
     * @return \self 
     */
    public static function create(){
        return new self(self::CREATE);
    }

    /**
     * @return \self 
     */
    public static function update(){
        return new self(self::UPDATE);
    }

    /**
     * @return \self 
     */
    public static function delete(){
        return new self(self::DELETE);
    }

    /**
     * @return \self 
     */
    public static function sort(){
        return new self(self::SORT);
    }

}
?>