<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-25 00:59:32                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StoryPeriod extends AutoStoryPeriod implements Prototyped, DAOConnected
	{
		/**
		 * @return StoryPeriod
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return StoryPeriodDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('StoryPeriodDAO');
		}
		
		/**
		 * @return ProtoStoryPeriod
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoStoryPeriod');
		}
		
		// your brilliant stuff goes here
	}
?>