<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2015-03-25 00:59:32                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class StoryRecord extends AutoStoryRecord implements Prototyped, DAOConnected
	{
		/**
		 * @return StoryRecord
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return StoryRecordDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('StoryRecordDAO');
		}
		
		/**
		 * @return ProtoStoryRecord
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoStoryRecord');
		}
		
		// your brilliant stuff goes here
	}
?>