<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2012-03-15 15:44:40                           *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class UserAccountIssue extends AutoUserAccountIssue implements Prototyped, DAOConnected
	{
		/**
		 * @return UserAccountIssue
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return UserAccountIssueDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('UserAccountIssueDAO');
		}
		
		/**
		 * @return ProtoUserAccountIssue
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoUserAccountIssue');
		}
		
		// your brilliant stuff goes here
                public function toArray() {
                    return array_merge(parent::toArray(),
                            array(
                                'value'=>$this->getValue(),
                                'balance'=>$this->getBalance(),
                                'description'=>$this->getDescription()
                            )
                    );
                }
	}
?>